export const getCountry = (country) => {
    const countries = {
        // América
        "AR": "Argentina",
        "BO": "Bolivia",
        "BR": "Brasil",
        "CL": "Chile",
        "CO": "Colombia",
        "CR": "Costa Rica",
        "CU": "Cuba",
        "DO": "República Dominicana",
        "EC": "Ecuador",
        "SV": "El Salvador",
        "GT": "Guatemala",
        "HT": "Haití",
        "HN": "Honduras",
        "JM": "Jamaica",
        "MX": "México",
        "NI": "Nicaragua",
        "PA": "Panamá",
        "PY": "Paraguay",
        "PE": "Perú",
        "PR": "Puerto Rico",
        "TT": "Trinidad y Tobago",
        "UY": "Uruguay",
        "VE": "Venezuela",
        "BB": "Barbados",
        "BZ": "Belice",
        "GY": "Guyana",
        "SR": "Surinam",
        "AG": "Antigua y Barbuda",
        "BS": "Bahamas",
        "DM": "Dominica",
        "GD": "Granada",
        "KN": "San Cristóbal y Nieves",
        "LC": "Santa Lucía",
        "VC": "San Vicente y las Granadinas",

        // América del Norte
        "CA": "Canadá",
        "US": "Estados Unidos",

        // Europa
        "AL": "Albania",
        "AD": "Andorra",
        "AT": "Austria",
        "BY": "Bielorrusia",
        "BE": "Bélgica",
        "BA": "Bosnia y Herzegovina",
        "BG": "Bulgaria",
        "HR": "Croacia",
        "CY": "Chipre",
        "CZ": "República Checa",
        "DK": "Dinamarca",
        "EE": "Estonia",
        "FI": "Finlandia",
        "FR": "Francia",
        "DE": "Alemania",
        "GR": "Grecia",
        "HU": "Hungría",
        "IS": "Islandia",
        "IE": "Irlanda",
        "IT": "Italia",
        "XK": "Kosovo",
        "LV": "Letonia",
        "LI": "Liechtenstein",
        "LT": "Lituania",
        "LU": "Luxemburgo",
        "MT": "Malta",
        "MD": "Moldavia",
        "MC": "Mónaco",
        "ME": "Montenegro",
        "NL": "Países Bajos",
        "MK": "Macedonia del Norte",
        "NO": "Noruega",
        "PL": "Polonia",
        "PT": "Portugal",
        "RO": "Rumanía",
        "RU": "Rusia",
        "SM": "San Marino",
        "RS": "Serbia",
        "SK": "Eslovaquia",
        "SI": "Eslovenia",
        "ES": "España",
        "SE": "Suecia",
        "CH": "Suiza",
        "UA": "Ucrania",
        "GB": "Reino Unido",
        "VA": "Ciudad del Vaticano",

        // Asia
        "AF": "Afganistán",
        "AM": "Armenia",
        "AZ": "Azerbaiyán",
        "BH": "Baréin",
        "BD": "Bangladés",
        "BT": "Bután",
        "BN": "Brunéi",
        "KH": "Camboya",
        "CN": "China",
        "GE": "Georgia",
        "IN": "India",
        "ID": "Indonesia",
        "IR": "Irán",
        "IQ": "Irak",
        "IL": "Israel",
        "JP": "Japón",
        "JO": "Jordania",
        "KZ": "Kazajistán",
        "KW": "Kuwait",
        "KG": "Kirguistán",
        "LA": "Laos",
        "LB": "Líbano",
        "MY": "Malasia",
        "MV": "Maldivas",
        "MN": "Mongolia",
        "MM": "Myanmar",
        "NP": "Nepal",
        "KP": "Corea del Norte",
        "OM": "Omán",
        "PK": "Pakistán",
        "PS": "Palestina",
        "PH": "Filipinas",
        "QA": "Catar",
        "SA": "Arabia Saudita",
        "SG": "Singapur",
        "KR": "Corea del Sur",
        "LK": "Sri Lanka",
        "SY": "Siria",
        "TW": "Taiwán",
        "TJ": "Tayikistán",
        "TH": "Tailandia",
        "TL": "Timor Oriental",
        "TM": "Turkmenistán",
        "AE": "Emiratos Árabes Unidos",
        "UZ": "Uzbekistán",
        "VN": "Vietnam",
        "YE": "Yemen",

        // África
        "DZ": "Argelia",
        "AO": "Angola",
        "BJ": "Benín",
        "BW": "Botsuana",
        "BF": "Burkina Faso",
        "BI": "Burundi",
        "CV": "Cabo Verde",
        "CM": "Camerún",
        "CF": "República Centroafricana",
        "TD": "Chad",
        "KM": "Comoras",
        "CG": "República del Congo",
        "CD": "República Democrática del Congo",
        "CI": "Costa de Marfil",
        "DJ": "Yibuti",
        "EG": "Egipto",
        "GQ": "Guinea Ecuatorial",
        "ER": "Eritrea",
        "SZ": "Esuatini",
        "ET": "Etiopía",
        "GA": "Gabón",
        "GM": "Gambia",
        "GH": "Ghana",
        "GN": "Guinea",
        "GW": "Guinea-Bisáu",
        "KE": "Kenia",
        "LS": "Lesoto",
        "LR": "Liberia",
        "LY": "Libia",
        "MG": "Madagascar",
        "MW": "Malaui",
        "ML": "Malí",
        "MR": "Mauritania",
        "MU": "Mauricio",
        "MA": "Marruecos",
        "MZ": "Mozambique",
        "NA": "Namibia",
        "NE": "Níger",
        "NG": "Nigeria",
        "RW": "Ruanda",
        "ST": "Santo Tomé y Príncipe",
        "SN": "Senegal",
        "SC": "Seychelles",
        "SL": "Sierra Leona",
        "SO": "Somalia",
        "ZA": "Sudáfrica",
        "SS": "Sudán del Sur",
        "SD": "Sudán",
        "TZ": "Tanzania",
        "TG": "Togo",
        "TN": "Túnez",
        "UG": "Uganda",
        "ZM": "Zambia",
        "ZW": "Zimbabue",

        // Oceanía
        "AU": "Australia",
        "FJ": "Fiyi",
        "KI": "Kiribati",
        "MH": "Islas Marshall",
        "FM": "Micronesia",
        "NR": "Nauru",
        "NZ": "Nueva Zelanda",
        "PW": "Palaos",
        "PG": "Papúa Nueva Guinea",
        "WS": "Samoa",
        "SB": "Islas Salomón",
        "TO": "Tonga",
        "TV": "Tuvalu",
        "VU": "Vanuatu",
    };

    return countries[country] ?? null;
};